name: build-and-release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write

jobs:
  docker:
    name: Build and Release to ghcr.io
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v4
    -
      name: Prepare env
      run: |
        commit_sha=$(git rev-parse --short HEAD)
        echo "commit_sha=$commit_sha"
        echo "commit_sha=$commit_sha" >> $GITHUB_ENV
        echo "docker_tag=${{ github.ref_name }}"
        echo "docker_tag=${{ github.ref_name }}" >> $GITHUB_ENV
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/arm64,linux/amd64,linux/arm/v7 #,windows/amd64
        push: true
        tags: |
          ghcr.io/markusgnigler/ghorg-sync:latest
          ghcr.io/markusgnigler/ghorg-sync:${{ env.commit_sha }}
          ghcr.io/markusgnigler/ghorg-sync:${{ env.docker_tag }}
    